language: node_js
node_js: 
  - 8
cache:
  directories:
    - "node_modules"

install:
  - npm i -g npm@latest
  - npm i -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: graphql-import-pipeline
      env: PACKAGE_LOCATION=packages/graphql-import
script: 
  - cd $PACKAGE_LOCATION
  - npm run build
  - npm run test